name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dotnet-auth:latest .
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dotnet-auth:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"
      - name: configure mkdir kubeconfig
        run: mkdir -p $HOME/.kube
      - name: Authenticate to Kubernetes cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | cat > $HOME/.kube/config
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/auth-docs auth-docs=exdec/dotnet-auth:latest -n sindika-dev
